The input files are derived from six files of the TSPLIB library:
fnl4461, pr1002, nrw1379, d18512, d15112, brd14051. 

From each file we created istances with different dimensions. 

For example, to generate an input file with 25 vertices from "fnl4461.tsp" we create three
files: fnl4461_25.tsp, match_fnl4461_25.mtc, ran_nn_25.str. 


(1) The first file represents the complete graph. This
file is a copy of the original file "fnl4461.tsp" with the only
difference that the parameter dimension inside it is set to 25. This
means that the graph is represented by only the first 25 vertices.


(2) The second file, "match_fnl4461_25.mtc", contains the information
to state what are the pickup and delivery vertices of the graph and
how they are associated. More precisely, on each row of the .mtc file
there are 3 numbers: the first is the ID of the vertex, the second
states whether this vertex is a pickup or a delivery (0 = delivery, 1
= pickup, 3 = depot) and the last number is the ID of the vertex
associated to it. For instance, if in the row there is: 3 0 7 this
means that vertex 3 is a delivery vertex and its pickup is vertex 7
(the only exception is for the depot whose row is: 0 3 0). The
definition of pickup and delivery vertices and the generation of
matchings were executed in a random way. 

(3) Finally, the last file represents the starting tour ( .str files) generated 
by the randomized nearest neighbour heuristic. 
This file is composed by a single column representing the tour (a sequence of vertex IDs)
and on the last row is shown the tour cost. 

The same structure is repeated for other dimensions and types of files.

Note that the starting tour of the tree-based algorithm proposed in paper 
"The Tree Representation for the Pickup and Delivery Traveling Salesman Problem with LIFO Loading"
is generated by (0^+, 1^+, 1^-, 2^+, 2^-, \ldots, n^+, n^-, 0^-). 
